import { Linkedin, Mail, MessageSquarePlus } from 'lucide-react';
import { DEVELOPER } from '../../utils/constants';

export default function Footer({ onOpenFeedback }) {
  return (
    <footer className="mt-auto border-t border-slate-200 px-4 py-5 text-center text-xs text-slate-500 sm:px-6 dark:border-slate-800 dark:text-slate-400">
      <p>HostelWallet - built for students who want their pocket money to last the whole month.</p>
      <p className="mt-1">
        Spending advice is generated by AI from your own numbers. Treat it as a nudge, not financial advice.
      </p>

      <div className="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-2">
        <span>
          Built by <span className="font-medium text-slate-600 dark:text-slate-300">{DEVELOPER.name}</span>
        </span>

        <a
          href={DEVELOPER.linkedin}
          target="_blank"
          rel="noreferrer noopener"
          className="inline-flex items-center gap-1.5 transition hover:text-brand-600 dark:hover:text-brand-400"
        >
          <Linkedin className="h-3.5 w-3.5" aria-hidden="true" />
          LinkedIn
        </a>

        <a
          href={`mailto:${DEVELOPER.email}?subject=HostelWallet`}
          className="inline-flex items-center gap-1.5 transition hover:text-brand-600 dark:hover:text-brand-400"
        >
          <Mail className="h-3.5 w-3.5" aria-hidden="true" />
          Email
        </a>

        {onOpenFeedback && (
          <button
            type="button"
            onClick={onOpenFeedback}
            className="inline-flex items-center gap-1.5 font-medium text-brand-700 transition hover:underline dark:text-brand-400"
          >
            <MessageSquarePlus className="h-3.5 w-3.5" aria-hidden="true" />
            Send feedback
          </button>
        )}
      </div>
    </footer>
  );
}
