export default function Footer() {
  return (
    <footer className="mt-auto border-t border-slate-200 px-4 py-5 text-center text-xs text-slate-500 sm:px-6 dark:border-slate-800 dark:text-slate-400">
      <p>
        HostelWallet - built for students who want their pocket money to last the whole month.
      </p>
      <p className="mt-1">
        Spending advice is generated by AI from your own numbers. Treat it as a nudge, not financial advice.
      </p>
    </footer>
  );
}
