import { AlertTriangle, PartyPopper, Sparkles, TrendingDown } from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import { categoryColor, categoryEmoji } from '../../utils/constants';
import { formatMoney } from '../../utils/format';

/**
 * Renders the structured advice payload from POST /api/ai/advice.
 * Because the backend asks Claude for JSON against a schema, this component
 * can lay the tips out properly instead of dumping a wall of text.
 */
export default function AdviceCard({ advice, currency = 'INR' }) {
  const { isDark } = useTheme();
  if (!advice) return null;

  const { headline, tips = [], warning, encouragement, aiPowered } = advice;
  const totalSaving = tips.reduce((sum, tip) => sum + (Number(tip.estimatedMonthlySaving) || 0), 0);

  return (
    <div className="space-y-4">
      <header className="flex items-start gap-3">
        <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white">
          <Sparkles className="h-5 w-5" />
        </span>
        <div>
          <p className="text-sm font-semibold text-slate-900 dark:text-slate-100">{headline}</p>
          {totalSaving > 0 && (
            <p className="mt-0.5 flex items-center gap-1.5 text-xs text-safe">
              <TrendingDown className="h-3.5 w-3.5" aria-hidden="true" />
              Following all of these could free up about {formatMoney(totalSaving, currency)} a month
            </p>
          )}
        </div>
      </header>

      {warning && (
        <div className="flex gap-2.5 rounded-xl border border-danger/25 bg-danger/10 p-3.5 dark:border-danger/30 dark:bg-danger/15">
          <AlertTriangle className="h-4 w-4 shrink-0 text-danger" aria-hidden="true" />
          <p className="text-xs font-medium text-danger">{warning}</p>
        </div>
      )}

      <ol className="space-y-3">
        {tips.map((tip, index) => (
          <li key={index} className="flex gap-3 rounded-xl border border-slate-200 p-3.5 dark:border-slate-800">
            <span
              className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-base"
              style={{ backgroundColor: `${categoryColor(tip.category, isDark)}1f` }}
              aria-hidden="true"
            >
              {categoryEmoji(tip.category)}
            </span>

            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-baseline gap-x-2">
                <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">
                  {index + 1}. {tip.title}
                </h3>
                {tip.estimatedMonthlySaving > 0 && (
                  <span className="rounded-full bg-safe/10 px-2 py-0.5 text-[11px] font-bold text-safe dark:bg-safe/15">
                    saves ~{formatMoney(tip.estimatedMonthlySaving, currency)}/mo
                  </span>
                )}
              </div>
              <p className="mt-1 text-xs leading-relaxed text-slate-600 dark:text-slate-400">{tip.detail}</p>
            </div>
          </li>
        ))}
      </ol>

      {encouragement && (
        <p className="flex items-center gap-2 rounded-xl bg-brand-50 px-3.5 py-3 text-xs font-medium text-brand-800 dark:bg-brand-500/10 dark:text-brand-300">
          <PartyPopper className="h-4 w-4 shrink-0" aria-hidden="true" />
          {encouragement}
        </p>
      )}

      {!aiPowered && (
        <p className="text-[11px] text-slate-400">
          Generated by the built-in advisor. Add an ANTHROPIC_API_KEY on the server for Claude-powered advice.
        </p>
      )}
    </div>
  );
}
